Repository rijinmk/vikas-portfolio, pull requests merged in 2024-04, with the labels that each got.

#15 feat(wip): basic structure of a section
  .eslintrc.ci.js
  .eslintrc.js
  src/components/Section/Section.module.css
  src/components/Section/Section.tsx
  src/pages/HomePage/HomePage.tsx
Labels: wip (do not merge)

#17 feat: storybook setup
  .eslintrc.ci.js
  .eslintrc.js
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  scripts/workflows/move_trello_tickets.js
  src/components/Section/Section.module.css
  src/components/Section/Section.tsx
  src/components/Section/Sections.stories.tsx
  src/pages/HomePage/HomePage.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  yarn.lock
Labels: wip (do not merge)

#28 fix: logo-update
  src/assets/Logo/vikas_logo.svg
  src/components/Layout/Header/Header.module.css
  src/global.css
Labels: ready for review

#22 feat: projects section heading
  src/components/SectionHeading/SectionHeading.module.css
  src/components/SectionHeading/SectionHeading.stories.ts
  src/components/SectionHeading/SectionHeading.tsx
  src/pages/ComponentGallery/ComponentGallery.tsx
Labels: wip (do not merge)

#21 feat: about me card (wip)
  .prettierrc
  src/assets/images/Profile-Icon/vigas-pragash.jpg
  src/components/AboutMeCard/AboutMeCard.module.css
  src/components/AboutMeCard/AboutMeCard.stories.tsx
  src/components/AboutMeCard/AboutMeCard.tsx
  src/global.css
  src/pages/ComponentGallery/ComponentGallery.tsx
  src/pages/ComponentGallery/data.json
  yarn.lock
Labels: wip (do not merge)

#26 feat: skillgrid (wip)
  src/components/SkillGrid/SkillGrid.module.css
  src/components/SkillGrid/SkillGrid.tsx
  src/pages/ComponentGallery/ComponentGallery.module.css
  src/pages/ComponentGallery/ComponentGallery.tsx
  src/pages/ComponentGallery/data.json
Labels: ready for review

#30 fix: file-restructured
  src/assets/fonts/avenir/avenir-light.ttf
  src/assets/fonts/lulo-clean/lulo-clean-one-bold.otf
  src/assets/fonts/lulo-clean/lulo-clean-one.otf
  src/assets/images/jpg/vigas-pragash.jpg
  src/assets/images/svg/HamburgerIcon.tsx
  src/assets/images/svg/vikas_logo.svg
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Layout.tsx
  src/global.css
  src/pages/ComponentGallery/ComponentGallery.tsx
Labels: ready for review

#32 fix: header-bug-fix
  src/components/Layout/Header/Header.tsx
Labels: ready for review

#33 fix: footer
  src/components/Layout/Footer/Footer.module.css
  src/components/Layout/Footer/Footer.tsx
  src/components/Layout/Layout.tsx
  src/pages/ComponentGallery/ComponentGallery.tsx
  src/pages/ComponentGallery/data.json
Labels: ready for review

#35 fix: overflow issue on component gallery
  .eslintrc.ci.js
  .eslintrc.js
  src/components/AboutMeCard/AboutMeCard.module.css
  src/components/NameIntro/NameIntro.module.css
  src/components/NameIntro/NameIntro.tsx
  src/pages/ComponentGallery/ComponentGallery.module.css
Labels: ready for review

#31 About Me Description Fix
  src/components/AboutMeCard/AboutMeCard.module.css
Labels: ready for review

#34 feat: contact card (wip)
  .eslintrc.ci.js
  .eslintrc.js
  src/assets/images/svg/linkedin_icon.svg
  src/components/AboutMeCard/AboutMeCard.module.css
  src/components/ContactCard/ContactCard.module.css
  src/components/ContactCard/ContactCard.tsx
  src/components/Layout/Footer/Footer.module.css
  src/components/Layout/Footer/Footer.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Layout.tsx
  src/components/NameIntro/NameIntro.module.css
  src/components/NameIntro/NameIntro.tsx
  src/components/SectionHeading/SectionHeading.tsx
  src/pages/ComponentGallery/ComponentGallery.module.css
  src/pages/ComponentGallery/ComponentGallery.tsx
  src/pages/ComponentGallery/data.json
Labels: wip (do not merge), ready for review
